services:
  - type: web
    name: mcs-mlt-f25-digit-recognition
    env: python
    plan: free
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app.main:app --workers 1 --threads 1 --timeout 180
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: OMP_NUM_THREADS
        value: 1
      - key: TF_NUM_INTRAOP_THREADS
        value: 1
      - key: TF_NUM_INTEROP_THREADS
        value: 1
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
