services:
  - type: web
    name: mcs-mlt-f25-digit-recognition
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app
    autoDeploy: true
